Name:           ros-kinetic-rosjava-build-tools
Version:        0.3.2
Release:        0%{?dist}
Summary:        ROS rosjava_build_tools package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rosjava_build_tools
Source0:        %{name}-%{version}.tar.gz

Requires:       ant
Requires:       java-1.8.0-openjdk
Requires:       ros-kinetic-catkin
BuildRequires:  ant
BuildRequires:  java-1.8.0-openjdk
BuildRequires:  ros-kinetic-catkin

%description
Simple tools and catkin modules for rosjava development.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Dec 29 2016 Daniel Stonier <d.stonier@gmail.com> - 0.3.2-0
- Autogenerated by Bloom

* Tue Dec 27 2016 Daniel Stonier <d.stonier@gmail.com> - 0.3.1-0
- Autogenerated by Bloom

* Fri Dec 23 2016 Daniel Stonier <d.stonier@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

